# Generated by Django 4.2.6 on 2023-10-17 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppCurso', '0002_regalo_foto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='regalo',
            name='foto',
        ),
    ]
