# Generated by Django 4.2.6 on 2023-10-17 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCurso', '0003_remove_regalo_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='pareja',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='parejas_fotos/'),
        ),
    ]
