# Generated by Django 4.2.6 on 2023-10-17 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCurso', '0005_alter_pareja_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pareja',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='avatares'),
        ),
    ]
