# Generated by Django 4.2.6 on 2023-10-19 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCurso', '0006_alter_pareja_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='regalo',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='regalos/'),
        ),
    ]
