# Generated by Django 4.2.6 on 2023-10-19 02:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppCurso', '0008_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
