# Generated by Django 4.2.6 on 2023-10-19 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCurso', '0010_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatares')),
            ],
        ),
    ]
