# Generated by Django 4.2.6 on 2023-10-19 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppCurso', '0011_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
