# Generated by Django 4.2.6 on 2023-10-19 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCurso', '0012_delete_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='regalo',
            name='imagen',
        ),
        migrations.AddField(
            model_name='regalo',
            name='imagen_regalo',
            field=models.ImageField(blank=True, null=True, upload_to='avatares'),
        ),
    ]
