# Generated by Django 4.2.6 on 2023-10-19 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCurso', '0013_remove_regalo_imagen_regalo_imagen_regalo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regalo',
            name='imagen_regalo',
            field=models.ImageField(blank=True, null=True, upload_to='regalos'),
        ),
    ]
