# Generated by Django 4.2.6 on 2023-10-19 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCurso', '0014_alter_regalo_imagen_regalo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='regalo',
            name='imagen_regalo',
        ),
        migrations.AddField(
            model_name='regalo',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='regalos'),
        ),
    ]
