# Generated by Django 4.2.6 on 2023-10-19 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppCurso', '0015_remove_regalo_imagen_regalo_regalo_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='regalo',
            name='imagen',
        ),
    ]
